services:
  - type: web
    name: edugen-backend
    env: node
    repo: https://github.com/yagnarashagan6/EDUGEN_AI
    rootDir: edugen-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false # Set this in the Render dashboard
